version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  build:
    commands:
      - make test
artifacts:
  discard-paths: yes
  files:
    - "**/*.template.yml"
    - "**/*.config.json"
    